# Generated by Django 4.2.23 on 2025-08-08 15:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('team_name', models.CharField(default='No Team!', max_length=30)),
                ('discord_name', models.CharField(default='NA', max_length=30)),
                ('slug', models.SlugField(blank=True)),
                ('rank', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('grandmaster', 'Grandmaster'), ('celestial', 'Celestial'), ('eternity', 'Eternity')], default='Bronze', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LfpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_rank', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('grandmaster', 'Grandmaster'), ('celestial', 'Celestial'), ('eternity', 'Eternity')], default='Bronze', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField(blank=True)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scrim.createteam')),
            ],
        ),
    ]
