# Generated by Django 4.2.23 on 2025-08-07 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sixteam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('discord_name', models.CharField(max_length=40)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('average_rank', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('grandmaster', 'Grandmaster'), ('celestial', 'Celestial'), ('eternity', 'Eternity')], default='Bronze', max_length=200)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userstat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('grandmaster', 'Grandmaster'), ('celestial', 'Celestial'), ('eternity', 'Eternity')], default='Bronze', max_length=200)),
                ('team_name', models.CharField(default='teamless!', max_length=30)),
                ('slug', models.SlugField(blank=True, max_length=30, unique=True)),
                ('role', models.CharField(choices=[('dps', 'DPS'), ('support', 'Support'), ('tank', 'Tank')], default='dps', max_length=30)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('team_status', models.IntegerField(choices=[(0, 'Playing'), (1, 'Sub')], default=1)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='The_Users_name', to=settings.AUTH_USER_MODEL)),
                ('six_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userstats', to='scrim.sixteam')),
            ],
            options={
                'ordering': ['created_on'],
                'unique_together': {('player', 'six_team')},
            },
        ),
        migrations.CreateModel(
            name='TeamMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scrim.sixteam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
