# Generated by Django 4.2.23 on 2025-08-08 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(default='No Team!', max_length=30)),
                ('discord_name', models.CharField(default='NA', max_length=30)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
