# Generated by Django 4.2.23 on 2025-08-08 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lfp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='scrim.lfpmodel')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
