# Generated by Django 4.2.23 on 2025-08-04 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0002_sixteam_teammembership_remove_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixteam',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
