# Generated by Django 4.2.23 on 2025-07-18 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0002_post_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userstat',
            options={'ordering': ['created_on']},
        ),
        migrations.RenameField(
            model_name='userstat',
            old_name='teamstatus',
            new_name='team_status',
        ),
        migrations.AlterField(
            model_name='userstat',
            name='rank',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('grandmaster', 'Grandmaster'), ('celestial', 'Celestial'), ('eternity', 'Eternity')], default='Bronze', max_length=200),
        ),
    ]
