# Generated by Django 4.2.23 on 2025-08-08 18:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0002_playerslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='createteam',
            name='team_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
