# Generated by Django 4.2.23 on 2025-08-08 12:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrim', '0002_createteam'),
    ]

    operations = [
        migrations.CreateModel(
            name='LfpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='userstat',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='player',
        ),
        migrations.RemoveField(
            model_name='userstat',
            name='six_team',
        ),
        migrations.AddField(
            model_name='createteam',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createteam',
            name='rank',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('grandmaster', 'Grandmaster'), ('celestial', 'Celestial'), ('eternity', 'Eternity')], default='Bronze', max_length=200),
        ),
        migrations.DeleteModel(
            name='Sixteam',
        ),
        migrations.DeleteModel(
            name='TeamMembership',
        ),
        migrations.DeleteModel(
            name='Userstat',
        ),
        migrations.AddField(
            model_name='lfpmodel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='scrim.createteam'),
        ),
    ]
