# Generated by Django 4.2.23 on 2025-08-05 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrim', '0003_sixteam_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixteam',
            name='is_lfp',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sixteam',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sixteam',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
