# Generated by Django 4.2.23 on 2025-08-08 18:41

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0003_createteam_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createteam',
            name='team_logo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
