# Generated by Django 4.2.23 on 2025-08-08 15:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0003_lfpmodel_alter_teammembership_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lfpmodel',
            name='average_rank',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('grandmaster', 'Grandmaster'), ('celestial', 'Celestial'), ('eternity', 'Eternity')], default='Bronze', max_length=200),
        ),
        migrations.AddField(
            model_name='lfpmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
