# Generated by Django 4.2.23 on 2025-08-09 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrim', '0004_alter_createteam_team_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='createteam',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
