# Generated by Django 4.2.23 on 2025-08-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0004_sixteam_is_lfp_alter_sixteam_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sixteam',
            name='average_rank',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond'), ('grandmaster', 'Grandmaster'), ('celestial', 'Celestial'), ('eternity', 'Eternity')], default='Bronze', max_length=200),
        ),
    ]
