# Generated by Django 4.2.23 on 2025-08-06 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0005_sixteam_average_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sixteam',
            name='is_lfp',
        ),
    ]
