# Generated by Django 4.2.23 on 2025-08-07 13:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0007_userstat_discord_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstat',
            name='discord_name',
        ),
        migrations.AddField(
            model_name='sixteam',
            name='discord_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
