# Generated by Django 4.2.23 on 2025-08-07 13:23

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scrim', '0008_remove_userstat_discord_name_sixteam_discord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='teammembership',
            unique_together={('team', 'user')},
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='teammembership',
            name='requested_at',
        ),
    ]
