# Generated by Django 4.2.23 on 2025-08-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrim', '0009_teammembership_joined_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembership',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
